### ISSUE TITLE
Add support for swiping left and right for touch devices

### ISSUE THREAD

**Issue by rvdleun** [rvdleun/aframe-presentation-component#1]
**Goal**
Add swipe navigation

**Description**
At the moment, the only way to move through the slides is by pressing left or right on the keyboard. For touch devices, there should be support to move back and forth by swiping to the left and right.

**Deliverables**
* Add support for swiping left or right in the `presentation` component to navigate through the slides.
* Add option in the schema to turn this feature on or off.

**Comment by ranndev** [comment]
Can I work on this?

**Comment by rvdleun** [comment]
Go for it, it would be appreciated :)

**Comment by ranndev** [comment]
Alright!
